# configuration file for dotnet-releaser
[msbuild]
project = "./dotnet-releaser/dotnet-releaser.csproj"
# Disable default packs - It will only publish NuGet and the Changelog
profile = "custom"
[github]
user = "xoofx"
repo = "dotnet-releaser"
[changelog]
path = "../changelog.md"