name: ci

env:
  PROJECT_NAME: dotnet-releaser

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'license.txt'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test (Debug)
      run: dotnet test src -c Debug

    - name: Pack
      run: |
          dotnet pack src -c Release

    - name: Publish
      if: github.event_name == 'push'
      run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
              ./src/dotnet-releaser/bin/Debug/net6.0/dotnet-releaser publish --nuget-token ${{secrets.NUGET_TOKEN}} --github-token  ${{secrets.TOKEN_GITHUB}} src/dotnet-releaser.toml
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]
          then
              ./src/dotnet-releaser/bin/Debug/net6.0/dotnet-releaser build --github-token ${{secrets.TOKEN_GITHUB}} src/dotnet-releaser.toml
          fi
