name: ci

env:
  PROJECT_NAME: dotnet-releaser

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'license.txt'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test (Debug)
      run: dotnet test src -c Debug

    - name: Self Build - Publish (main only)
      if: github.event_name == 'push'
      run: |
        ./src/dotnet-releaser/bin/Debug/net6.0/dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" src/dotnet-releaser.toml
