name: ci

env:
  PROJECT_NAME: dotnet-releaser

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'license.txt'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test (Debug)
      run: dotnet test src -c Debug -p:DotNetReleaserBinCi=true

    - name: Pack
      run: |
          dotnet pack src -c Release

    - name: Publish
      if: github.event_name == 'push'
      run: |
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+" ) {
              src/dotnet-releaser/Bin/Debug/net6.0/dotnet-releaser publish --nuget-token ${{secrets.NUGET_TOKEN}} --github-token  ${{secrets.TOKEN_GITHUB}} ./src/dotnet-releaser/dotnet-releaser.toml
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
